from sqlalchemy import inspect, text

from app.core.config import settings
from app.core.database import create_sync_database
from app.models import Base


LEGACY_TABLES = (
    "dealers", "dms_systems", "inbound_documents", "standardized_invoices", "invoice_line_items",
)
LINKS = (
    ("inbound_documents", "dealer_id", "dealers"),
    ("inbound_documents", "dms_id", "dms_systems"),
    ("standardized_invoices", "document_id", "inbound_documents"),
    ("invoice_line_items", "invoice_id", "standardized_invoices"),
)


def convert_legacy_schema(connection):
    connection.exec_driver_sql("LOCK TABLE dealers, dms_systems, inbound_documents, standardized_invoices, invoice_line_items IN ACCESS EXCLUSIVE MODE")
    conflict = connection.scalar(text("""
        SELECT EXISTS (
            SELECT 1 FROM standardized_invoices AS invoice
            JOIN inbound_documents AS document ON document.id = invoice.document_id
            WHERE invoice.supplier_dealer_id <> document.dealer_id
        )
    """))
    if conflict:
        raise ValueError("Reconcile invoice suppliers with sending dealers before changing the schema")
    connection.exec_driver_sql("DROP TRIGGER IF EXISTS set_invoice_updated_at ON standardized_invoices")
    connection.exec_driver_sql("ALTER TABLE inbound_documents ADD COLUMN raw_payload JSONB, ADD COLUMN error_message TEXT")
    tables = set(inspect(connection).get_table_names(schema="public"))
    if "processing_runs" in tables:
        connection.exec_driver_sql("""
            UPDATE inbound_documents AS document
            SET error_message = latest.error_message, status = 'FAILED'
            FROM (
                SELECT DISTINCT ON (document_id) document_id, status, error_message
                FROM processing_runs ORDER BY document_id, attempt_number DESC
            ) AS latest
            WHERE latest.document_id = document.id AND latest.status = 'FAILED'
        """)
        connection.exec_driver_sql("DROP TABLE processing_runs")
    connection.exec_driver_sql("ALTER TABLE inbound_documents DROP CONSTRAINT ck_inbound_documents_status")
    connection.exec_driver_sql("""
        ALTER TABLE inbound_documents ADD CONSTRAINT ck_inbound_documents_status
        CHECK (status IN ('RECEIVED', 'PROCESSING', 'COMPLETED', 'REVIEW_REQUIRED', 'FAILED'))
    """)
    connection.exec_driver_sql("""
        UPDATE inbound_documents AS document SET status = 'REVIEW_REQUIRED'
        FROM standardized_invoices AS invoice
        WHERE invoice.document_id = document.id AND document.status <> 'FAILED'
        AND (invoice.validation_status = 'REVIEW_REQUIRED' OR invoice.review_status = 'PENDING')
    """)
    connection.exec_driver_sql("""
        UPDATE standardized_invoices AS invoice
        SET canonical_payload = (invoice.canonical_payload - 'supplier_dealer_id')
            || jsonb_build_object('supplier_dealer_code', dealer.dealer_code)
        FROM inbound_documents AS document
        JOIN dealers AS dealer ON dealer.id = document.dealer_id
        WHERE invoice.document_id = document.id
    """)
    connection.exec_driver_sql("""
        UPDATE standardized_invoices AS invoice
        SET canonical_payload = jsonb_set(invoice.canonical_payload, '{line_items}', (
            SELECT COALESCE(jsonb_agg(
                (entry.value - 'vin') || jsonb_build_object('chassis_number',
                    COALESCE(entry.value -> 'chassis_number', entry.value -> 'vin', 'null'::jsonb))
                ORDER BY entry.ordinality
            ), '[]'::jsonb)
            FROM jsonb_array_elements(invoice.canonical_payload -> 'line_items')
                WITH ORDINALITY AS entry(value, ordinality)
        ))
        WHERE jsonb_typeof(invoice.canonical_payload -> 'line_items') = 'array'
    """)
    connection.exec_driver_sql("ALTER TABLE standardized_invoices DROP CONSTRAINT fk_standardized_invoices_supplier_dealer_id_dealers")
    connection.exec_driver_sql("DROP INDEX ix_standardized_invoices_number_supplier")
    connection.exec_driver_sql("DROP INDEX ix_standardized_invoices_validation_review")
    connection.exec_driver_sql("ALTER TABLE standardized_invoices DROP COLUMN supplier_dealer_id")
    connection.exec_driver_sql("ALTER TABLE inbound_documents DROP COLUMN storage_provider")
    for table in LEGACY_TABLES:
        connection.exec_driver_sql(f"ALTER TABLE {table} ADD COLUMN _integer_id BIGINT GENERATED BY DEFAULT AS IDENTITY")
    for table, column, parent in LINKS:
        connection.exec_driver_sql(f"ALTER TABLE {table} ADD COLUMN _integer_{column} BIGINT")
        connection.exec_driver_sql(
            f"UPDATE {table} AS child SET _integer_{column} = parent._integer_id "
            f"FROM {parent} AS parent WHERE child.{column} = parent.id"
        )
        connection.exec_driver_sql(f"ALTER TABLE {table} ALTER COLUMN _integer_{column} SET NOT NULL")
        connection.exec_driver_sql(f"ALTER TABLE {table} DROP CONSTRAINT fk_{table}_{column}_{parent}")
    connection.exec_driver_sql("ALTER TABLE standardized_invoices DROP CONSTRAINT uq_standardized_invoices_document_id")
    connection.exec_driver_sql("ALTER TABLE invoice_line_items DROP CONSTRAINT uq_invoice_line_items_invoice_line")
    connection.exec_driver_sql("DROP INDEX ix_inbound_documents_dealer_received")
    for table, column, parent in LINKS:
        connection.exec_driver_sql(f"ALTER TABLE {table} DROP COLUMN {column}")
        connection.exec_driver_sql(f"ALTER TABLE {table} RENAME COLUMN _integer_{column} TO {column}")
    for table in LEGACY_TABLES:
        connection.exec_driver_sql(f"ALTER TABLE {table} DROP CONSTRAINT pk_{table}")
        connection.exec_driver_sql(f"ALTER TABLE {table} DROP COLUMN id")
        connection.exec_driver_sql(f"ALTER TABLE {table} RENAME COLUMN _integer_id TO id")
        connection.exec_driver_sql(f"ALTER TABLE {table} ADD CONSTRAINT pk_{table} PRIMARY KEY (id)")
    for table, column, parent in LINKS:
        connection.exec_driver_sql(
            f"ALTER TABLE {table} ADD CONSTRAINT fk_{table}_{column}_{parent} "
            f"FOREIGN KEY ({column}) REFERENCES {parent}(id)"
        )
    connection.exec_driver_sql("ALTER TABLE standardized_invoices ADD CONSTRAINT uq_standardized_invoices_document_id UNIQUE (document_id)")
    connection.exec_driver_sql("ALTER TABLE invoice_line_items ADD CONSTRAINT uq_invoice_line_items_invoice_line UNIQUE (invoice_id, line_number)")
    connection.exec_driver_sql("CREATE INDEX ix_inbound_documents_dealer_received ON inbound_documents (dealer_id, received_at)")
    connection.exec_driver_sql("CREATE INDEX ix_standardized_invoices_number_validation ON standardized_invoices (invoice_number, validation_status)")
    connection.exec_driver_sql("ALTER TABLE invoice_line_items RENAME COLUMN vin TO chassis_number")
    connection.exec_driver_sql("ALTER TABLE invoice_line_items ALTER COLUMN chassis_number TYPE VARCHAR(50)")


def setup_database(engine):
    with engine.begin() as connection:
        connection.exec_driver_sql("SET LOCAL search_path TO public")
        connection.exec_driver_sql("SET LOCAL lock_timeout = '10s'")
        connection.exec_driver_sql("SELECT pg_advisory_xact_lock(741239019)")
        inspector = inspect(connection)
        tables = set(inspector.get_table_names(schema="public"))
        unknown = tables - set(Base.metadata.tables) - {"alembic_version", "processing_runs"}
        if unknown:
            raise ValueError("Unexpected tables exist; review them before applying the final schema")
        legacy = {
            table for table in LEGACY_TABLES if table in tables
            and str(next(column for column in inspector.get_columns(table) if column["name"] == "id")["type"]).lower() == "uuid"
        }
        if legacy:
            if legacy != set(LEGACY_TABLES) or {"mapping_configs", "validation_rules"} & tables:
                raise ValueError("Mixed legacy schema found; reconcile it before applying the final schema")
            convert_legacy_schema(connection)
        elif "processing_runs" in tables:
            raise ValueError("Unexpected processing history with integer keys; review it before removal")
        Base.metadata.create_all(connection)
        connection.exec_driver_sql("""
            CREATE OR REPLACE FUNCTION public.onedms_set_invoice_updated_at()
            RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                NEW.updated_at = clock_timestamp();
                RETURN NEW;
            END;
            $$
        """)
        connection.exec_driver_sql("DROP TRIGGER IF EXISTS set_invoice_updated_at ON standardized_invoices")
        connection.exec_driver_sql("""
            CREATE TRIGGER set_invoice_updated_at BEFORE UPDATE ON standardized_invoices
            FOR EACH ROW EXECUTE FUNCTION public.onedms_set_invoice_updated_at()
        """)
        connection.exec_driver_sql("DROP TABLE IF EXISTS alembic_version")
        final_tables = set(inspect(connection).get_table_names(schema="public"))
        if final_tables != set(Base.metadata.tables):
            raise ValueError("Final table set does not match the seven-table design")
    return sorted(final_tables)


def main():
    engine = None
    try:
        engine = create_sync_database(settings)
        tables = setup_database(engine)
        print("Schema applied successfully. Public tables:")
        for table in tables:
            print(f"- {table}")
    except Exception as error:
        detail = f" {error}" if isinstance(error, ValueError) else ""
        raise SystemExit(
            f"Schema update failed ({type(error).__name__}); transaction rolled back.{detail}"
        ) from None
    finally:
        if engine is not None:
            engine.dispose()


if __name__ == "__main__":
    main()